// Comprehensive demo data - 195+ countries with difficulty levels
// difficulty: 1 = Kolay (Avrupa + Bilinen), 2-3 = Orta, 4-5 = Zor (Az bilinen)
const DEMO_COUNTRIES = [
    // ===== DIFFICULTY 1: KOLAY - Avrupa + Çok Bilinen =====
    { cca2: "TR", difficulty: 1, name: { common: "Türkiye" }, flags: { png: "https://flagcdn.com/w320/tr.png" }, region: "Asia", subregion: "Western Asia", population: 84339067 },
    { cca2: "DE", difficulty: 1, name: { common: "Almanya" }, flags: { png: "https://flagcdn.com/w320/de.png" }, region: "Europe", subregion: "Western Europe", population: 83240525 },
    { cca2: "FR", difficulty: 1, name: { common: "Fransa" }, flags: { png: "https://flagcdn.com/w320/fr.png" }, region: "Europe", subregion: "Western Europe", population: 67391582 },
    { cca2: "IT", difficulty: 1, name: { common: "İtalya" }, flags: { png: "https://flagcdn.com/w320/it.png" }, region: "Europe", subregion: "Southern Europe", population: 59554023 },
    { cca2: "ES", difficulty: 1, name: { common: "İspanya" }, flags: { png: "https://flagcdn.com/w320/es.png" }, region: "Europe", subregion: "Southern Europe", population: 47351567 },
    { cca2: "GB", difficulty: 1, name: { common: "Birleşik Krallık" }, flags: { png: "https://flagcdn.com/w320/gb.png" }, region: "Europe", subregion: "Northern Europe", population: 67215293 },
    { cca2: "NL", difficulty: 1, name: { common: "Hollanda" }, flags: { png: "https://flagcdn.com/w320/nl.png" }, region: "Europe", subregion: "Western Europe", population: 17441139 },
    { cca2: "BE", difficulty: 1, name: { common: "Belçika" }, flags: { png: "https://flagcdn.com/w320/be.png" }, region: "Europe", subregion: "Western Europe", population: 11555997 },
    { cca2: "CH", difficulty: 1, name: { common: "İsviçre" }, flags: { png: "https://flagcdn.com/w320/ch.png" }, region: "Europe", subregion: "Western Europe", population: 8636896 },
    { cca2: "AT", difficulty: 1, name: { common: "Avusturya" }, flags: { png: "https://flagcdn.com/w320/at.png" }, region: "Europe", subregion: "Central Europe", population: 8917205 },
    { cca2: "SE", difficulty: 1, name: { common: "İsveç" }, flags: { png: "https://flagcdn.com/w320/se.png" }, region: "Europe", subregion: "Northern Europe", population: 10353442 },
    { cca2: "NO", difficulty: 1, name: { common: "Norveç" }, flags: { png: "https://flagcdn.com/w320/no.png" }, region: "Europe", subregion: "Northern Europe", population: 5379475 },
    { cca2: "DK", difficulty: 1, name: { common: "Danimarka" }, flags: { png: "https://flagcdn.com/w320/dk.png" }, region: "Europe", subregion: "Northern Europe", population: 5831404 },
    { cca2: "FI", difficulty: 1, name: { common: "Finlandiya" }, flags: { png: "https://flagcdn.com/w320/fi.png" }, region: "Europe", subregion: "Northern Europe", population: 5530719 },
    { cca2: "PL", difficulty: 1, name: { common: "Polonya" }, flags: { png: "https://flagcdn.com/w320/pl.png" }, region: "Europe", subregion: "Central Europe", population: 37950802 },
    { cca2: "RU", difficulty: 1, name: { common: "Rusya" }, flags: { png: "https://flagcdn.com/w320/ru.png" }, region: "Europe", subregion: "Eastern Europe", population: 144104080 },
    { cca2: "GR", difficulty: 1, name: { common: "Yunanistan" }, flags: { png: "https://flagcdn.com/w320/gr.png" }, region: "Europe", subregion: "Southern Europe", population: 10715549 },
    { cca2: "PT", difficulty: 1, name: { common: "Portekiz" }, flags: { png: "https://flagcdn.com/w320/pt.png" }, region: "Europe", subregion: "Southern Europe", population: 10305564 },
    { cca2: "IE", difficulty: 1, name: { common: "İrlanda" }, flags: { png: "https://flagcdn.com/w320/ie.png" }, region: "Europe", subregion: "Northern Europe", population: 4994724 },
    { cca2: "US", difficulty: 1, name: { common: "Amerika Birleşik Devletleri" }, flags: { png: "https://flagcdn.com/w320/us.png" }, region: "Americas", subregion: "North America", population: 329484123 },
    { cca2: "CA", difficulty: 1, name: { common: "Kanada" }, flags: { png: "https://flagcdn.com/w320/ca.png" }, region: "Americas", subregion: "North America", population: 38005238 },
    { cca2: "JP", difficulty: 1, name: { common: "Japonya" }, flags: { png: "https://flagcdn.com/w320/jp.png" }, region: "Asia", subregion: "Eastern Asia", population: 125836021 },
    { cca2: "CN", difficulty: 1, name: { common: "Çin" }, flags: { png: "https://flagcdn.com/w320/cn.png" }, region: "Asia", subregion: "Eastern Asia", population: 1402112000 },
    { cca2: "BR", difficulty: 1, name: { common: "Brezilya" }, flags: { png: "https://flagcdn.com/w320/br.png" }, region: "Americas", subregion: "South America", population: 212559409 },
    { cca2: "AU", difficulty: 1, name: { common: "Avustralya" }, flags: { png: "https://flagcdn.com/w320/au.png" }, region: "Oceania", subregion: "Australia and New Zealand", population: 25687041 },

    // ===== DIFFICULTY 2: ORTA-KOLAY =====
    { cca2: "RO", difficulty: 2, name: { common: "Romanya" }, flags: { png: "https://flagcdn.com/w320/ro.png" }, region: "Europe", subregion: "Southeast Europe", population: 19286123 },
    { cca2: "CZ", difficulty: 2, name: { common: "Çek Cumhuriyeti" }, flags: { png: "https://flagcdn.com/w320/cz.png" }, region: "Europe", subregion: "Central Europe", population: 10698896 },
    { cca2: "HU", difficulty: 2, name: { common: "Macaristan" }, flags: { png: "https://flagcdn.com/w320/hu.png" }, region: "Europe", subregion: "Central Europe", population: 9749763 },
    { cca2: "UA", difficulty: 2, name: { common: "Ukrayna" }, flags: { png: "https://flagcdn.com/w320/ua.png" }, region: "Europe", subregion: "Eastern Europe", population: 44134693 },
    { cca2: "RS", difficulty: 2, name: { common: "Sırbistan" }, flags: { png: "https://flagcdn.com/w320/rs.png" }, region: "Europe", subregion: "Southeast Europe", population: 6908224 },
    { cca2: "HR", difficulty: 2, name: { common: "Hırvatistan" }, flags: { png: "https://flagcdn.com/w320/hr.png" }, region: "Europe", subregion: "Southeast Europe", population: 4047200 },
    { cca2: "BG", difficulty: 2, name: { common: "Bulgaristan" }, flags: { png: "https://flagcdn.com/w320/bg.png" }, region: "Europe", subregion: "Southeast Europe", population: 6927288 },
    { cca2: "IS", difficulty: 2, name: { common: "İzlanda" }, flags: { png: "https://flagcdn.com/w320/is.png" }, region: "Europe", subregion: "Northern Europe", population: 366425 },
    { cca2: "MX", difficulty: 2, name: { common: "Meksika" }, flags: { png: "https://flagcdn.com/w320/mx.png" }, region: "Americas", subregion: "North America", population: 128932753 },
    { cca2: "AR", difficulty: 2, name: { common: "Arjantin" }, flags: { png: "https://flagcdn.com/w320/ar.png" }, region: "Americas", subregion: "South America", population: 45376763 },
    { cca2: "KR", difficulty: 2, name: { common: "Güney Kore" }, flags: { png: "https://flagcdn.com/w320/kr.png" }, region: "Asia", subregion: "Eastern Asia", population: 51780579 },
    { cca2: "IN", difficulty: 2, name: { common: "Hindistan" }, flags: { png: "https://flagcdn.com/w320/in.png" }, region: "Asia", subregion: "Southern Asia", population: 1380004385 },
    { cca2: "EG", difficulty: 2, name: { common: "Mısır" }, flags: { png: "https://flagcdn.com/w320/eg.png" }, region: "Africa", subregion: "Northern Africa", population: 102334403 },
    { cca2: "ZA", difficulty: 2, name: { common: "Güney Afrika" }, flags: { png: "https://flagcdn.com/w320/za.png" }, region: "Africa", subregion: "Southern Africa", population: 59308690 },
    { cca2: "SA", difficulty: 2, name: { common: "Suudi Arabistan" }, flags: { png: "https://flagcdn.com/w320/sa.png" }, region: "Asia", subregion: "Western Asia", population: 34813867 },
    { cca2: "AE", difficulty: 2, name: { common: "Birleşik Arap Emirlikleri" }, flags: { png: "https://flagcdn.com/w320/ae.png" }, region: "Asia", subregion: "Western Asia", population: 9890400 },
    { cca2: "NZ", difficulty: 2, name: { common: "Yeni Zelanda" }, flags: { png: "https://flagcdn.com/w320/nz.png" }, region: "Oceania", subregion: "Australia and New Zealand", population: 5084300 },
    { cca2: "IL", difficulty: 2, name: { common: "İsrail" }, flags: { png: "https://flagcdn.com/w320/il.png" }, region: "Asia", subregion: "Western Asia", population: 9216900 },
    { cca2: "IR", difficulty: 2, name: { common: "İran" }, flags: { png: "https://flagcdn.com/w320/ir.png" }, region: "Asia", subregion: "Southern Asia", population: 83992953 },
    { cca2: "ID", difficulty: 2, name: { common: "Endonezya" }, flags: { png: "https://flagcdn.com/w320/id.png" }, region: "Asia", subregion: "South-Eastern Asia", population: 273523621 },
    { cca2: "TH", difficulty: 2, name: { common: "Tayland" }, flags: { png: "https://flagcdn.com/w320/th.png" }, region: "Asia", subregion: "South-Eastern Asia", population: 69799978 },
    { cca2: "VN", difficulty: 2, name: { common: "Vietnam" }, flags: { png: "https://flagcdn.com/w320/vn.png" }, region: "Asia", subregion: "South-Eastern Asia", population: 97338583 },
    { cca2: "PH", difficulty: 2, name: { common: "Filipinler" }, flags: { png: "https://flagcdn.com/w320/ph.png" }, region: "Asia", subregion: "South-Eastern Asia", population: 109581085 },
    { cca2: "MY", difficulty: 2, name: { common: "Malezya" }, flags: { png: "https://flagcdn.com/w320/my.png" }, region: "Asia", subregion: "South-Eastern Asia", population: 32365998 },
    { cca2: "SG", difficulty: 2, name: { common: "Singapur" }, flags: { png: "https://flagcdn.com/w320/sg.png" }, region: "Asia", subregion: "South-Eastern Asia", population: 5685807 },
    { cca2: "PK", difficulty: 2, name: { common: "Pakistan" }, flags: { png: "https://flagcdn.com/w320/pk.png" }, region: "Asia", subregion: "Southern Asia", population: 220892331 },
    { cca2: "CU", difficulty: 2, name: { common: "Küba" }, flags: { png: "https://flagcdn.com/w320/cu.png" }, region: "Americas", subregion: "Caribbean", population: 11326616 },
    { cca2: "CO", difficulty: 2, name: { common: "Kolombiya" }, flags: { png: "https://flagcdn.com/w320/co.png" }, region: "Americas", subregion: "South America", population: 50882884 },
    { cca2: "CL", difficulty: 2, name: { common: "Şili" }, flags: { png: "https://flagcdn.com/w320/cl.png" }, region: "Americas", subregion: "South America", population: 19116209 },
    { cca2: "PE", difficulty: 2, name: { common: "Peru" }, flags: { png: "https://flagcdn.com/w320/pe.png" }, region: "Americas", subregion: "South America", population: 32971846 },

    // ===== DIFFICULTY 3: ORTA =====
    { cca2: "AL", difficulty: 3, name: { common: "Arnavutluk" }, flags: { png: "https://flagcdn.com/w320/al.png" }, region: "Europe", subregion: "Southeast Europe", population: 2877800 },
    { cca2: "MK", difficulty: 3, name: { common: "Kuzey Makedonya" }, flags: { png: "https://flagcdn.com/w320/mk.png" }, region: "Europe", subregion: "Southeast Europe", population: 2083374 },
    { cca2: "SI", difficulty: 3, name: { common: "Slovenya" }, flags: { png: "https://flagcdn.com/w320/si.png" }, region: "Europe", subregion: "Central Europe", population: 2100126 },
    { cca2: "SK", difficulty: 3, name: { common: "Slovakya" }, flags: { png: "https://flagcdn.com/w320/sk.png" }, region: "Europe", subregion: "Central Europe", population: 5458827 },
    { cca2: "BA", difficulty: 3, name: { common: "Bosna Hersek" }, flags: { png: "https://flagcdn.com/w320/ba.png" }, region: "Europe", subregion: "Southeast Europe", population: 3280815 },
    { cca2: "ME", difficulty: 3, name: { common: "Karadağ" }, flags: { png: "https://flagcdn.com/w320/me.png" }, region: "Europe", subregion: "Southeast Europe", population: 621718 },
    { cca2: "XK", difficulty: 3, name: { common: "Kosova" }, flags: { png: "https://flagcdn.com/w320/xk.png" }, region: "Europe", subregion: "Southeast Europe", population: 1873000 },
    { cca2: "MD", difficulty: 3, name: { common: "Moldova" }, flags: { png: "https://flagcdn.com/w320/md.png" }, region: "Europe", subregion: "Eastern Europe", population: 2617820 },
    { cca2: "BY", difficulty: 3, name: { common: "Belarus" }, flags: { png: "https://flagcdn.com/w320/by.png" }, region: "Europe", subregion: "Eastern Europe", population: 9398861 },
    { cca2: "LT", difficulty: 3, name: { common: "Litvanya" }, flags: { png: "https://flagcdn.com/w320/lt.png" }, region: "Europe", subregion: "Northern Europe", population: 2794700 },
    { cca2: "LV", difficulty: 3, name: { common: "Letonya" }, flags: { png: "https://flagcdn.com/w320/lv.png" }, region: "Europe", subregion: "Northern Europe", population: 1901548 },
    { cca2: "EE", difficulty: 3, name: { common: "Estonya" }, flags: { png: "https://flagcdn.com/w320/ee.png" }, region: "Europe", subregion: "Northern Europe", population: 1331057 },
    { cca2: "LU", difficulty: 3, name: { common: "Lüksemburg" }, flags: { png: "https://flagcdn.com/w320/lu.png" }, region: "Europe", subregion: "Western Europe", population: 632275 },
    { cca2: "MT", difficulty: 3, name: { common: "Malta" }, flags: { png: "https://flagcdn.com/w320/mt.png" }, region: "Europe", subregion: "Southern Europe", population: 525285 },
    { cca2: "CY", difficulty: 3, name: { common: "Kıbrıs" }, flags: { png: "https://flagcdn.com/w320/cy.png" }, region: "Europe", subregion: "Eastern Europe", population: 1207361 },
    { cca2: "AZ", difficulty: 3, name: { common: "Azerbaycan" }, flags: { png: "https://flagcdn.com/w320/az.png" }, region: "Asia", subregion: "Western Asia", population: 10110116 },
    { cca2: "GE", difficulty: 3, name: { common: "Gürcistan" }, flags: { png: "https://flagcdn.com/w320/ge.png" }, region: "Asia", subregion: "Western Asia", population: 3714000 },
    { cca2: "AM", difficulty: 3, name: { common: "Ermenistan" }, flags: { png: "https://flagcdn.com/w320/am.png" }, region: "Asia", subregion: "Western Asia", population: 2963234 },
    { cca2: "KZ", difficulty: 3, name: { common: "Kazakistan" }, flags: { png: "https://flagcdn.com/w320/kz.png" }, region: "Asia", subregion: "Central Asia", population: 18754440 },
    { cca2: "UZ", difficulty: 3, name: { common: "Özbekistan" }, flags: { png: "https://flagcdn.com/w320/uz.png" }, region: "Asia", subregion: "Central Asia", population: 34232050 },
    { cca2: "NG", difficulty: 3, name: { common: "Nijerya" }, flags: { png: "https://flagcdn.com/w320/ng.png" }, region: "Africa", subregion: "Western Africa", population: 206139587 },
    { cca2: "KE", difficulty: 3, name: { common: "Kenya" }, flags: { png: "https://flagcdn.com/w320/ke.png" }, region: "Africa", subregion: "Eastern Africa", population: 53771300 },
    { cca2: "ET", difficulty: 3, name: { common: "Etiyopya" }, flags: { png: "https://flagcdn.com/w320/et.png" }, region: "Africa", subregion: "Eastern Africa", population: 114963583 },
    { cca2: "DZ", difficulty: 3, name: { common: "Cezayir" }, flags: { png: "https://flagcdn.com/w320/dz.png" }, region: "Africa", subregion: "Northern Africa", population: 43851043 },
    { cca2: "MA", difficulty: 3, name: { common: "Fas" }, flags: { png: "https://flagcdn.com/w320/ma.png" }, region: "Africa", subregion: "Northern Africa", population: 36910558 },
    { cca2: "TN", difficulty: 3, name: { common: "Tunus" }, flags: { png: "https://flagcdn.com/w320/tn.png" }, region: "Africa", subregion: "Northern Africa", population: 11818618 },
    { cca2: "IQ", difficulty: 3, name: { common: "Irak" }, flags: { png: "https://flagcdn.com/w320/iq.png" }, region: "Asia", subregion: "Western Asia", population: 40222503 },
    { cca2: "SY", difficulty: 3, name: { common: "Suriye" }, flags: { png: "https://flagcdn.com/w320/sy.png" }, region: "Asia", subregion: "Western Asia", population: 17500657 },
    { cca2: "LB", difficulty: 3, name: { common: "Lübnan" }, flags: { png: "https://flagcdn.com/w320/lb.png" }, region: "Asia", subregion: "Western Asia", population: 6825442 },
    { cca2: "JO", difficulty: 3, name: { common: "Ürdün" }, flags: { png: "https://flagcdn.com/w320/jo.png" }, region: "Asia", subregion: "Western Asia", population: 10203140 },
    { cca2: "QA", difficulty: 3, name: { common: "Katar" }, flags: { png: "https://flagcdn.com/w320/qa.png" }, region: "Asia", subregion: "Western Asia", population: 2881060 },
    { cca2: "KW", difficulty: 3, name: { common: "Kuveyt" }, flags: { png: "https://flagcdn.com/w320/kw.png" }, region: "Asia", subregion: "Western Asia", population: 4270563 },
    { cca2: "BD", difficulty: 3, name: { common: "Bangladeş" }, flags: { png: "https://flagcdn.com/w320/bd.png" }, region: "Asia", subregion: "Southern Asia", population: 164689383 },
    { cca2: "NP", difficulty: 3, name: { common: "Nepal" }, flags: { png: "https://flagcdn.com/w320/np.png" }, region: "Asia", subregion: "Southern Asia", population: 29136808 },
    { cca2: "LK", difficulty: 3, name: { common: "Sri Lanka" }, flags: { png: "https://flagcdn.com/w320/lk.png" }, region: "Asia", subregion: "Southern Asia", population: 21919000 },
    { cca2: "MM", difficulty: 3, name: { common: "Myanmar" }, flags: { png: "https://flagcdn.com/w320/mm.png" }, region: "Asia", subregion: "South-Eastern Asia", population: 54409800 },
    { cca2: "KH", difficulty: 3, name: { common: "Kamboçya" }, flags: { png: "https://flagcdn.com/w320/kh.png" }, region: "Asia", subregion: "South-Eastern Asia", population: 16718965 },
    { cca2: "VE", difficulty: 3, name: { common: "Venezuela" }, flags: { png: "https://flagcdn.com/w320/ve.png" }, region: "Americas", subregion: "South America", population: 28435943 },
    { cca2: "EC", difficulty: 3, name: { common: "Ekvador" }, flags: { png: "https://flagcdn.com/w320/ec.png" }, region: "Americas", subregion: "South America", population: 17643060 },
    { cca2: "UY", difficulty: 3, name: { common: "Uruguay" }, flags: { png: "https://flagcdn.com/w320/uy.png" }, region: "Americas", subregion: "South America", population: 3473727 },
    { cca2: "PY", difficulty: 3, name: { common: "Paraguay" }, flags: { png: "https://flagcdn.com/w320/py.png" }, region: "Americas", subregion: "South America", population: 7132530 },
    { cca2: "BO", difficulty: 3, name: { common: "Bolivya" }, flags: { png: "https://flagcdn.com/w320/bo.png" }, region: "Americas", subregion: "South America", population: 11673029 },
    { cca2: "JM", difficulty: 3, name: { common: "Jamaika" }, flags: { png: "https://flagcdn.com/w320/jm.png" }, region: "Americas", subregion: "Caribbean", population: 2961161 },
    { cca2: "TW", difficulty: 3, name: { common: "Tayvan" }, flags: { png: "https://flagcdn.com/w320/tw.png" }, region: "Asia", subregion: "Eastern Asia", population: 23503349 },
    { cca2: "HK", difficulty: 3, name: { common: "Hong Kong" }, flags: { png: "https://flagcdn.com/w320/hk.png" }, region: "Asia", subregion: "Eastern Asia", population: 7481800 },
    { cca2: "KP", difficulty: 3, name: { common: "Kuzey Kore" }, flags: { png: "https://flagcdn.com/w320/kp.png" }, region: "Asia", subregion: "Eastern Asia", population: 25778815 },
    { cca2: "MN", difficulty: 3, name: { common: "Moğolistan" }, flags: { png: "https://flagcdn.com/w320/mn.png" }, region: "Asia", subregion: "Eastern Asia", population: 3278292 },

    // ===== DIFFICULTY 4: ORTA-ZOR =====
    { cca2: "MC", difficulty: 4, name: { common: "Monaco" }, flags: { png: "https://flagcdn.com/w320/mc.png" }, region: "Europe", subregion: "Western Europe", population: 39244 },
    { cca2: "AD", difficulty: 4, name: { common: "Andorra" }, flags: { png: "https://flagcdn.com/w320/ad.png" }, region: "Europe", subregion: "Southern Europe", population: 77265 },
    { cca2: "SM", difficulty: 4, name: { common: "San Marino" }, flags: { png: "https://flagcdn.com/w320/sm.png" }, region: "Europe", subregion: "Southern Europe", population: 33938 },
    { cca2: "VA", difficulty: 4, name: { common: "Vatikan" }, flags: { png: "https://flagcdn.com/w320/va.png" }, region: "Europe", subregion: "Southern Europe", population: 451 },
    { cca2: "LI", difficulty: 4, name: { common: "Lihtenştayn" }, flags: { png: "https://flagcdn.com/w320/li.png" }, region: "Europe", subregion: "Western Europe", population: 38137 },
    { cca2: "TZ", difficulty: 4, name: { common: "Tanzanya" }, flags: { png: "https://flagcdn.com/w320/tz.png" }, region: "Africa", subregion: "Eastern Africa", population: 59734213 },
    { cca2: "GH", difficulty: 4, name: { common: "Gana" }, flags: { png: "https://flagcdn.com/w320/gh.png" }, region: "Africa", subregion: "Western Africa", population: 31072945 },
    { cca2: "UG", difficulty: 4, name: { common: "Uganda" }, flags: { png: "https://flagcdn.com/w320/ug.png" }, region: "Africa", subregion: "Eastern Africa", population: 45741000 },
    { cca2: "SN", difficulty: 4, name: { common: "Senegal" }, flags: { png: "https://flagcdn.com/w320/sn.png" }, region: "Africa", subregion: "Western Africa", population: 16743930 },
    { cca2: "CM", difficulty: 4, name: { common: "Kamerun" }, flags: { png: "https://flagcdn.com/w320/cm.png" }, region: "Africa", subregion: "Middle Africa", population: 26545864 },
    { cca2: "ZW", difficulty: 4, name: { common: "Zimbabve" }, flags: { png: "https://flagcdn.com/w320/zw.png" }, region: "Africa", subregion: "Eastern Africa", population: 14862927 },
    { cca2: "LY", difficulty: 4, name: { common: "Libya" }, flags: { png: "https://flagcdn.com/w320/ly.png" }, region: "Africa", subregion: "Northern Africa", population: 6871287 },
    { cca2: "SD", difficulty: 4, name: { common: "Sudan" }, flags: { png: "https://flagcdn.com/w320/sd.png" }, region: "Africa", subregion: "Northern Africa", population: 43849260 },
    { cca2: "AO", difficulty: 4, name: { common: "Angola" }, flags: { png: "https://flagcdn.com/w320/ao.png" }, region: "Africa", subregion: "Middle Africa", population: 32866272 },
    { cca2: "MZ", difficulty: 4, name: { common: "Mozambik" }, flags: { png: "https://flagcdn.com/w320/mz.png" }, region: "Africa", subregion: "Eastern Africa", population: 31255435 },
    { cca2: "MG", difficulty: 4, name: { common: "Madagaskar" }, flags: { png: "https://flagcdn.com/w320/mg.png" }, region: "Africa", subregion: "Eastern Africa", population: 27691019 },
    { cca2: "CI", difficulty: 4, name: { common: "Fildişi Sahili" }, flags: { png: "https://flagcdn.com/w320/ci.png" }, region: "Africa", subregion: "Western Africa", population: 26378275 },
    { cca2: "NE", difficulty: 4, name: { common: "Nijer" }, flags: { png: "https://flagcdn.com/w320/ne.png" }, region: "Africa", subregion: "Western Africa", population: 24206636 },
    { cca2: "ML", difficulty: 4, name: { common: "Mali" }, flags: { png: "https://flagcdn.com/w320/ml.png" }, region: "Africa", subregion: "Western Africa", population: 20250834 },
    { cca2: "BF", difficulty: 4, name: { common: "Burkina Faso" }, flags: { png: "https://flagcdn.com/w320/bf.png" }, region: "Africa", subregion: "Western Africa", population: 20903278 },
    { cca2: "ZM", difficulty: 4, name: { common: "Zambiya" }, flags: { png: "https://flagcdn.com/w320/zm.png" }, region: "Africa", subregion: "Eastern Africa", population: 18383956 },
    { cca2: "MW", difficulty: 4, name: { common: "Malavi" }, flags: { png: "https://flagcdn.com/w320/mw.png" }, region: "Africa", subregion: "Eastern Africa", population: 19129955 },
    { cca2: "SO", difficulty: 4, name: { common: "Somali" }, flags: { png: "https://flagcdn.com/w320/so.png" }, region: "Africa", subregion: "Eastern Africa", population: 15893219 },
    { cca2: "RW", difficulty: 4, name: { common: "Ruanda" }, flags: { png: "https://flagcdn.com/w320/rw.png" }, region: "Africa", subregion: "Eastern Africa", population: 12952209 },
    { cca2: "BW", difficulty: 4, name: { common: "Botsvana" }, flags: { png: "https://flagcdn.com/w320/bw.png" }, region: "Africa", subregion: "Southern Africa", population: 2351625 },
    { cca2: "NA", difficulty: 4, name: { common: "Namibya" }, flags: { png: "https://flagcdn.com/w320/na.png" }, region: "Africa", subregion: "Southern Africa", population: 2540916 },
    { cca2: "OM", difficulty: 4, name: { common: "Umman" }, flags: { png: "https://flagcdn.com/w320/om.png" }, region: "Asia", subregion: "Western Asia", population: 5106622 },
    { cca2: "BH", difficulty: 4, name: { common: "Bahreyn" }, flags: { png: "https://flagcdn.com/w320/bh.png" }, region: "Asia", subregion: "Western Asia", population: 1701583 },
    { cca2: "YE", difficulty: 4, name: { common: "Yemen" }, flags: { png: "https://flagcdn.com/w320/ye.png" }, region: "Asia", subregion: "Western Asia", population: 29825968 },
    { cca2: "AF", difficulty: 4, name: { common: "Afganistan" }, flags: { png: "https://flagcdn.com/w320/af.png" }, region: "Asia", subregion: "Southern Asia", population: 38928341 },
    { cca2: "TM", difficulty: 4, name: { common: "Türkmenistan" }, flags: { png: "https://flagcdn.com/w320/tm.png" }, region: "Asia", subregion: "Central Asia", population: 6031187 },
    { cca2: "TJ", difficulty: 4, name: { common: "Tacikistan" }, flags: { png: "https://flagcdn.com/w320/tj.png" }, region: "Asia", subregion: "Central Asia", population: 9537642 },
    { cca2: "KG", difficulty: 4, name: { common: "Kırgızistan" }, flags: { png: "https://flagcdn.com/w320/kg.png" }, region: "Asia", subregion: "Central Asia", population: 6591600 },
    { cca2: "LA", difficulty: 4, name: { common: "Laos" }, flags: { png: "https://flagcdn.com/w320/la.png" }, region: "Asia", subregion: "South-Eastern Asia", population: 7275556 },
    { cca2: "BN", difficulty: 4, name: { common: "Brunei" }, flags: { png: "https://flagcdn.com/w320/bn.png" }, region: "Asia", subregion: "South-Eastern Asia", population: 437483 },
    { cca2: "BT", difficulty: 4, name: { common: "Butan" }, flags: { png: "https://flagcdn.com/w320/bt.png" }, region: "Asia", subregion: "Southern Asia", population: 771612 },
    { cca2: "MV", difficulty: 4, name: { common: "Maldivler" }, flags: { png: "https://flagcdn.com/w320/mv.png" }, region: "Asia", subregion: "Southern Asia", population: 540542 },
    { cca2: "FJ", difficulty: 4, name: { common: "Fiji" }, flags: { png: "https://flagcdn.com/w320/fj.png" }, region: "Oceania", subregion: "Melanesia", population: 896444 },
    { cca2: "PG", difficulty: 4, name: { common: "Papua Yeni Gine" }, flags: { png: "https://flagcdn.com/w320/pg.png" }, region: "Oceania", subregion: "Melanesia", population: 8947027 },
    { cca2: "CR", difficulty: 4, name: { common: "Kosta Rika" }, flags: { png: "https://flagcdn.com/w320/cr.png" }, region: "Americas", subregion: "Central America", population: 5094114 },
    { cca2: "PA", difficulty: 4, name: { common: "Panama" }, flags: { png: "https://flagcdn.com/w320/pa.png" }, region: "Americas", subregion: "Central America", population: 4314768 },
    { cca2: "GT", difficulty: 4, name: { common: "Guatemala" }, flags: { png: "https://flagcdn.com/w320/gt.png" }, region: "Americas", subregion: "Central America", population: 16858333 },
    { cca2: "HN", difficulty: 4, name: { common: "Honduras" }, flags: { png: "https://flagcdn.com/w320/hn.png" }, region: "Americas", subregion: "Central America", population: 9904608 },
    { cca2: "SV", difficulty: 4, name: { common: "El Salvador" }, flags: { png: "https://flagcdn.com/w320/sv.png" }, region: "Americas", subregion: "Central America", population: 6486201 },
    { cca2: "NI", difficulty: 4, name: { common: "Nikaragua" }, flags: { png: "https://flagcdn.com/w320/ni.png" }, region: "Americas", subregion: "Central America", population: 6624554 },
    { cca2: "DO", difficulty: 4, name: { common: "Dominik Cumhuriyeti" }, flags: { png: "https://flagcdn.com/w320/do.png" }, region: "Americas", subregion: "Caribbean", population: 10847904 },
    { cca2: "HT", difficulty: 4, name: { common: "Haiti" }, flags: { png: "https://flagcdn.com/w320/ht.png" }, region: "Americas", subregion: "Caribbean", population: 11402533 },
    { cca2: "PR", difficulty: 4, name: { common: "Porto Riko" }, flags: { png: "https://flagcdn.com/w320/pr.png" }, region: "Americas", subregion: "Caribbean", population: 3285874 },
    { cca2: "TT", difficulty: 4, name: { common: "Trinidad ve Tobago" }, flags: { png: "https://flagcdn.com/w320/tt.png" }, region: "Americas", subregion: "Caribbean", population: 1399491 },
    { cca2: "GY", difficulty: 4, name: { common: "Guyana" }, flags: { png: "https://flagcdn.com/w320/gy.png" }, region: "Americas", subregion: "South America", population: 786559 },
    { cca2: "SR", difficulty: 4, name: { common: "Surinam" }, flags: { png: "https://flagcdn.com/w320/sr.png" }, region: "Americas", subregion: "South America", population: 586634 },

    // ===== DIFFICULTY 5: ZOR - Az Bilinen =====
    { cca2: "TD", difficulty: 5, name: { common: "Çad" }, flags: { png: "https://flagcdn.com/w320/td.png" }, region: "Africa", subregion: "Middle Africa", population: 16425859 },
    { cca2: "CG", difficulty: 5, name: { common: "Kongo" }, flags: { png: "https://flagcdn.com/w320/cg.png" }, region: "Africa", subregion: "Middle Africa", population: 5518092 },
    { cca2: "CD", difficulty: 5, name: { common: "Demokratik Kongo" }, flags: { png: "https://flagcdn.com/w320/cd.png" }, region: "Africa", subregion: "Middle Africa", population: 89561404 },
    { cca2: "CF", difficulty: 5, name: { common: "Orta Afrika Cumhuriyeti" }, flags: { png: "https://flagcdn.com/w320/cf.png" }, region: "Africa", subregion: "Middle Africa", population: 4829764 },
    { cca2: "GA", difficulty: 5, name: { common: "Gabon" }, flags: { png: "https://flagcdn.com/w320/ga.png" }, region: "Africa", subregion: "Middle Africa", population: 2225728 },
    { cca2: "GQ", difficulty: 5, name: { common: "Ekvator Ginesi" }, flags: { png: "https://flagcdn.com/w320/gq.png" }, region: "Africa", subregion: "Middle Africa", population: 1402985 },
    { cca2: "SS", difficulty: 5, name: { common: "Güney Sudan" }, flags: { png: "https://flagcdn.com/w320/ss.png" }, region: "Africa", subregion: "Eastern Africa", population: 11193729 },
    { cca2: "ER", difficulty: 5, name: { common: "Eritre" }, flags: { png: "https://flagcdn.com/w320/er.png" }, region: "Africa", subregion: "Eastern Africa", population: 3546427 },
    { cca2: "DJ", difficulty: 5, name: { common: "Cibuti" }, flags: { png: "https://flagcdn.com/w320/dj.png" }, region: "Africa", subregion: "Eastern Africa", population: 988002 },
    { cca2: "BI", difficulty: 5, name: { common: "Burundi" }, flags: { png: "https://flagcdn.com/w320/bi.png" }, region: "Africa", subregion: "Eastern Africa", population: 11890781 },
    { cca2: "MR", difficulty: 5, name: { common: "Moritanya" }, flags: { png: "https://flagcdn.com/w320/mr.png" }, region: "Africa", subregion: "Western Africa", population: 4649660 },
    { cca2: "GN", difficulty: 5, name: { common: "Gine" }, flags: { png: "https://flagcdn.com/w320/gn.png" }, region: "Africa", subregion: "Western Africa", population: 13132792 },
    { cca2: "GW", difficulty: 5, name: { common: "Gine-Bissau" }, flags: { png: "https://flagcdn.com/w320/gw.png" }, region: "Africa", subregion: "Western Africa", population: 1967998 },
    { cca2: "SL", difficulty: 5, name: { common: "Sierra Leone" }, flags: { png: "https://flagcdn.com/w320/sl.png" }, region: "Africa", subregion: "Western Africa", population: 7976985 },
    { cca2: "LR", difficulty: 5, name: { common: "Liberya" }, flags: { png: "https://flagcdn.com/w320/lr.png" }, region: "Africa", subregion: "Western Africa", population: 5057677 },
    { cca2: "TG", difficulty: 5, name: { common: "Togo" }, flags: { png: "https://flagcdn.com/w320/tg.png" }, region: "Africa", subregion: "Western Africa", population: 8278737 },
    { cca2: "BJ", difficulty: 5, name: { common: "Benin" }, flags: { png: "https://flagcdn.com/w320/bj.png" }, region: "Africa", subregion: "Western Africa", population: 12123198 },
    { cca2: "GM", difficulty: 5, name: { common: "Gambiya" }, flags: { png: "https://flagcdn.com/w320/gm.png" }, region: "Africa", subregion: "Western Africa", population: 2416664 },
    { cca2: "CV", difficulty: 5, name: { common: "Yeşil Burun Adaları" }, flags: { png: "https://flagcdn.com/w320/cv.png" }, region: "Africa", subregion: "Western Africa", population: 555988 },
    { cca2: "ST", difficulty: 5, name: { common: "São Tomé ve Príncipe" }, flags: { png: "https://flagcdn.com/w320/st.png" }, region: "Africa", subregion: "Middle Africa", population: 219161 },
    { cca2: "SZ", difficulty: 5, name: { common: "Esvatini" }, flags: { png: "https://flagcdn.com/w320/sz.png" }, region: "Africa", subregion: "Southern Africa", population: 1160164 },
    { cca2: "LS", difficulty: 5, name: { common: "Lesotho" }, flags: { png: "https://flagcdn.com/w320/ls.png" }, region: "Africa", subregion: "Southern Africa", population: 2142252 },
    { cca2: "MU", difficulty: 5, name: { common: "Mauritius" }, flags: { png: "https://flagcdn.com/w320/mu.png" }, region: "Africa", subregion: "Eastern Africa", population: 1265740 },
    { cca2: "SC", difficulty: 5, name: { common: "Seyşeller" }, flags: { png: "https://flagcdn.com/w320/sc.png" }, region: "Africa", subregion: "Eastern Africa", population: 98462 },
    { cca2: "KM", difficulty: 5, name: { common: "Komorlar" }, flags: { png: "https://flagcdn.com/w320/km.png" }, region: "Africa", subregion: "Eastern Africa", population: 869595 },
    { cca2: "PS", difficulty: 5, name: { common: "Filistin" }, flags: { png: "https://flagcdn.com/w320/ps.png" }, region: "Asia", subregion: "Western Asia", population: 5101416 },
    { cca2: "TL", difficulty: 5, name: { common: "Doğu Timor" }, flags: { png: "https://flagcdn.com/w320/tl.png" }, region: "Asia", subregion: "South-Eastern Asia", population: 1318442 },
    { cca2: "WS", difficulty: 5, name: { common: "Samoa" }, flags: { png: "https://flagcdn.com/w320/ws.png" }, region: "Oceania", subregion: "Polynesia", population: 198410 },
    { cca2: "TO", difficulty: 5, name: { common: "Tonga" }, flags: { png: "https://flagcdn.com/w320/to.png" }, region: "Oceania", subregion: "Polynesia", population: 105697 },
    { cca2: "VU", difficulty: 5, name: { common: "Vanuatu" }, flags: { png: "https://flagcdn.com/w320/vu.png" }, region: "Oceania", subregion: "Melanesia", population: 307150 },
    { cca2: "SB", difficulty: 5, name: { common: "Solomon Adaları" }, flags: { png: "https://flagcdn.com/w320/sb.png" }, region: "Oceania", subregion: "Melanesia", population: 686878 },
    { cca2: "KI", difficulty: 5, name: { common: "Kiribati" }, flags: { png: "https://flagcdn.com/w320/ki.png" }, region: "Oceania", subregion: "Micronesia", population: 119446 },
    { cca2: "FM", difficulty: 5, name: { common: "Mikronezya" }, flags: { png: "https://flagcdn.com/w320/fm.png" }, region: "Oceania", subregion: "Micronesia", population: 115021 },
    { cca2: "MH", difficulty: 5, name: { common: "Marshall Adaları" }, flags: { png: "https://flagcdn.com/w320/mh.png" }, region: "Oceania", subregion: "Micronesia", population: 59194 },
    { cca2: "PW", difficulty: 5, name: { common: "Palau" }, flags: { png: "https://flagcdn.com/w320/pw.png" }, region: "Oceania", subregion: "Micronesia", population: 18092 },
    { cca2: "NR", difficulty: 5, name: { common: "Nauru" }, flags: { png: "https://flagcdn.com/w320/nr.png" }, region: "Oceania", subregion: "Micronesia", population: 10834 },
    { cca2: "TV", difficulty: 5, name: { common: "Tuvalu" }, flags: { png: "https://flagcdn.com/w320/tv.png" }, region: "Oceania", subregion: "Polynesia", population: 11792 },
    { cca2: "BZ", difficulty: 5, name: { common: "Belize" }, flags: { png: "https://flagcdn.com/w320/bz.png" }, region: "Americas", subregion: "Central America", population: 397621 },
    { cca2: "BB", difficulty: 5, name: { common: "Barbados" }, flags: { png: "https://flagcdn.com/w320/bb.png" }, region: "Americas", subregion: "Caribbean", population: 287371 },
    { cca2: "BS", difficulty: 5, name: { common: "Bahamalar" }, flags: { png: "https://flagcdn.com/w320/bs.png" }, region: "Americas", subregion: "Caribbean", population: 393248 },
    { cca2: "LC", difficulty: 5, name: { common: "Saint Lucia" }, flags: { png: "https://flagcdn.com/w320/lc.png" }, region: "Americas", subregion: "Caribbean", population: 183629 },
    { cca2: "VC", difficulty: 5, name: { common: "Saint Vincent" }, flags: { png: "https://flagcdn.com/w320/vc.png" }, region: "Americas", subregion: "Caribbean", population: 110947 },
    { cca2: "GD", difficulty: 5, name: { common: "Grenada" }, flags: { png: "https://flagcdn.com/w320/gd.png" }, region: "Americas", subregion: "Caribbean", population: 112519 },
    { cca2: "AG", difficulty: 5, name: { common: "Antigua ve Barbuda" }, flags: { png: "https://flagcdn.com/w320/ag.png" }, region: "Americas", subregion: "Caribbean", population: 97928 },
    { cca2: "KN", difficulty: 5, name: { common: "Saint Kitts ve Nevis" }, flags: { png: "https://flagcdn.com/w320/kn.png" }, region: "Americas", subregion: "Caribbean", population: 53192 },
    { cca2: "DM", difficulty: 5, name: { common: "Dominika" }, flags: { png: "https://flagcdn.com/w320/dm.png" }, region: "Americas", subregion: "Caribbean", population: 71991 },
];
